// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymcyjwuxqqdooighbnwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltY3lqd3V4cXFkb29pZ2hibnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTAyNTYsImV4cCI6MjA3MzY2NjI1Nn0.xXIrP_CtSQl-lrmsTc9FXgHaHP7t1xh0yXUg_Wa53_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});